
name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
runs:
  using: 'node16'
  main: 'main.js'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo content
      uses: actions/checkout@v2 # checkout the repository content to github runner.
    - name: setup python
      uses: actions/setup-python@v2
      with:
         python-version: 3.8 #install the python needed
    - name: Build and Test VPC in dev
      run: |
        python deploy_NetworkDev1.py
      env:
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       AWS_DEFAULT_REGION: 'us-east-1'

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - name: Deploy VPC to prod
      run: |
        python deploy_NetworkDev1.py
      env:
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       AWS_DEFAULT_REGION: 'us-east-1'

